### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by yangsubinn** [29th-WE-SOPT-iOS-Part/YangSuBin#13]
## 📌  Feature Issue
데이터 연결 심화, UIGestureRecognizer

## 📝  To-do
- [ ] imageView에 tap gesture recognizer, present 화면 전환 연결
- [ ] 화면 전환시 데이터 전달 (imageView, 영상 title, 조회수, 업로드 시간)
- [ ] 전환된 뷰에서 dismiss
